Added parameters overriding via maven CLI arguments
denysord88/drill-web-test-framework pull request #16
Opened 2018-09-20 11:34 UTC by denysord88

@agozhiy could you please review this PR?

2018-09-20 13:27 UTC, agozhiy requested changes

2018-09-20 13:27 UTC, agozhiy commented on src/test/java/org/apache/drillui/test/framework/initial/TestProperties.java
> +
Please remove newlines between the properties

2018-09-20 13:27 UTC, agozhiy commented on src/test/java/org/apache/drillui/test/framework/initial/TestProperties.java
> +      if(OS.equals("WINDOWS")) webdriversPath += ".exe";
Should be moved to a separate method.

2018-09-20 13:27 UTC, agozhiy commented on src/test/java/org/apache/drillui/test/framework/initial/TestProperties.java
> +    if(os.contains("nix") || os.contains("nux") || os.contains("aix")) return "LINUX";
Change to the if ... else statements. And please use braces.

2018-09-20 13:27 UTC, agozhiy commented on src/test/java/org/apache/drillui/test/framework/initial/TestProperties.java
> +    if(property == null) property = initFile.getProperty(parameterName);
Braces.

2018-09-20 15:12 UTC, denysord88 commented
@agozhiy could you please review changes by your comments?

2018-09-21 08:58 UTC, agozhiy approved these changes

2018-09-21 08:58 UTC, agozhiy commented
+1

2018-09-21 09:01 UTC, merged