Added authorization tests
denysord88/drill-web-test-framework pull request #4
Opened 2018-07-25 11:35 UTC by denysord88

@agozhiy could you please review changes?

2018-07-25 14:16 UTC, agozhiy requested changes

2018-07-25 14:16 UTC, agozhiy commented on src/test/java/pages/LoginNavigatePage.java
> +  public void openMainLoginPage() {
Page methods that open a new page should return the corresponding page object.

2018-07-25 14:16 UTC, agozhiy commented on src/test/java/pages/LoginNavigatePage.java
> +public class LoginNavigatePage extends BasePage {
This page is not needed at all. We can use NavigationPage instead

2018-07-25 14:16 UTC, agozhiy commented on src/test/java/pages/LoginPage.java
> +  }
Please extract this method to Steps. Page objects shouldn't contain any logic.

2018-07-25 14:16 UTC, agozhiy commented on src/test/java/pages/LogoutNavigatePage.java
> +public class LogoutNavigatePage extends BasePage {
The page is not needed. Please use NavigatioPage.

2018-07-25 14:16 UTC, agozhiy commented on src/test/java/pages/MainLoginPage.java
> +public class MainLoginPage extends BasePage {
Please rename pages MainLoginPage and LoginPage.
They have different purpose. MainLoginPage is for choosing auth method (Form, SPNEGO etc), while LoginPage is used for entering credentials for Form authentication.

2018-07-25 14:16 UTC, agozhiy commented on src/test/java/testng/unsecure/BaseUnsecureTest.java
> +    AuthSteps.login();
Add an option check for secured Drill.

2018-07-26 09:56 UTC, denysord88 commented
Updated

2018-07-26 10:31 UTC, agozhiy approved these changes

2018-07-26 10:32 UTC, agozhiy commented
+1 LGTM

2018-07-26 10:32 UTC, merged