Selenoid support
denysord88/drill-web-test-framework pull request #43
Opened 2019-06-12 10:24 UTC by denysord88

Added connection params to the Selenoid RemoteWebDriver for Chrome and Firefox browsers.
Changed clipboard handling in the sendKeys() method to support Selenoid container.

2019-06-12 10:26 UTC, denysord88 commented
@agozhiy @Atri0 please, review the PR.
Tests can be executed for the Firefox browser on Jenkins:
http://10.234.238.21:8080/job/Web_Framework_Tests/

2019-06-12 10:34 UTC, Atri0 commented
+1 LGTM

2019-06-12 11:07 UTC, agozhiy requested changes

2019-06-12 11:07 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/properties/PropertiesConst.java
> +
Remove newline.

2019-06-12 11:07 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +          DesiredCapabilities capabilities = new DesiredCapabilities();
Better move this code to a separate method to avoid repetition. You have only two parameters here: browser name and version.

2019-06-12 11:07 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +          sessionId = ((RemoteWebDriver)getDriver()).getSessionId().toString();
```suggestion
          sessionId = ((RemoteWebDriver) getDriver()).getSessionId().toString();
```

2019-06-12 11:07 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +      } catch (MalformedURLException e) {
Need to be handled within the init() method.

2019-06-12 13:17 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/properties/PropertiesConst.java
> +
Done

2019-06-12 13:37 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +          DesiredCapabilities capabilities = new DesiredCapabilities();
Done

2019-06-12 13:38 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +      } catch (MalformedURLException e) {
Done

2019-06-12 15:17 UTC, denysord88 commented
@agozhiy please, review the changes.

2019-06-12 15:41 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +          DesiredCapabilities capabilities = new DesiredCapabilities();
I suggest to change the return type to WebDriver and use a ternary operator instead of if.

2019-06-12 15:53 UTC, agozhiy requested changes

2019-06-12 15:53 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +      e.printStackTrace();
```suggestion
      throw new RuntimeException(e);
```

2019-06-13 15:45 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +          sessionId = ((RemoteWebDriver)getDriver()).getSessionId().toString();
Done

2019-06-13 15:45 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +          DesiredCapabilities capabilities = new DesiredCapabilities();
Done

2019-06-13 15:48 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +      e.printStackTrace();
Done

2019-06-13 15:48 UTC, denysord88 commented
@agozhiy please, review the changes.

2019-06-14 11:54 UTC, agozhiy requested changes

2019-06-14 11:54 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +            "webdriver." +
The indent is too big.

2019-06-14 11:54 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +    WebDriver remoteDriver = null;
```suggestion
    RemoteWebDriver remoteDriver = null;
```

2019-06-14 11:54 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +  private static WebDriver setupRemoteWebDriver(String driverVersion) {
```suggestion
  private static WebDriver getRemoteWebDriver(String driverVersion) {
```

2019-06-14 11:54 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +    sessionId = ((RemoteWebDriver) remoteDriver).getSessionId().toString();
```suggestion
    sessionId = remoteDriver.getSessionId().toString();
```

2019-06-14 12:46 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +    WebDriver remoteDriver = null;
Done

2019-06-14 12:49 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +            "webdriver." +
Done

2019-06-14 12:51 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +  private static WebDriver setupRemoteWebDriver(String driverVersion) {
Done

2019-06-14 12:51 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/web_ui/WebBrowser.java
> +    sessionId = ((RemoteWebDriver) remoteDriver).getSessionId().toString();
Done

2019-06-14 13:03 UTC, agozhiy commented
+1.

2019-06-14 13:03 UTC, agozhiy approved these changes

2019-06-14 13:20 UTC, merged