Added backup and restore methods to Drill storage plugins
denysord88/drill-web-test-framework pull request #46
Opened 2019-06-18 17:47 UTC by denysord88

2019-06-19 13:39 UTC, denysord88 commented
@agozhiy @Atri0 please review the PR.

2019-06-20 08:55 UTC, Atri0 commented
LGTM

2019-06-20 14:51 UTC, agozhiy requested changes

2019-06-20 14:51 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/rest_api/data/RestBaseSteps.java
> +  public static void backupPlugin(String pluginName) {
Should be moved to RestStorageSteps.

2019-06-20 14:51 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/rest_api/data/RestBaseSteps.java
> +  public static void restorePlugins() {
Should be moved to RestStorageSteps.

2019-06-20 14:51 UTC, agozhiy commented on src/test/java/org/apache/drill_web_test_framework/rest_api/data/RestBaseSteps.java
> +  private static String getStoragePlugin(String pluginName) {
Should be moved to RestStorageSteps.

2019-06-20 15:15 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/rest_api/data/RestBaseSteps.java
> +  public static void backupPlugin(String pluginName) {
Done

2019-06-20 15:16 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/rest_api/data/RestBaseSteps.java
> +  public static void restorePlugins() {
Done

2019-06-20 15:16 UTC, denysord88 commented on src/test/java/org/apache/drill_web_test_framework/rest_api/data/RestBaseSteps.java
> +  private static String getStoragePlugin(String pluginName) {
Done

2019-06-20 15:16 UTC, denysord88 commented
@agozhiy please review changes.

2019-06-21 13:08 UTC, agozhiy commented
+1.

2019-06-21 13:08 UTC, agozhiy approved these changes

2019-06-21 13:40 UTC, merged